# ------------------------------------------
# Default Administrator User
# Email:    admin@example.com
# Password: changeme
# ------------------------------------------

version: "3"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80'
      - '443:443'
      # Admin Web Port:
      - '81:81'
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      - ./frontend:/home/app/frontend
  frontend:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    environment:
      - GRAPH=https://api.arqsacasa820.com/
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile-s
    image: nodejs
    restart: unless-stopped
    environment:
      - PORT=4000
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASS=password
      - DB_NAME=Sacasa
      - DB_PORT=5432
      - GOOGLE_APPLICATION_CREDENTIALS=/home/node/app/sacasa-41319-firebase-adminsdk-bd34d-c3d64e7125.json
    volumes:
      - ./backend/backend:/home/node/app
  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: Sacasa
      POSTGRES_PASSWORD: password
    volumes:
      - ./database:/var/lib/postgresql/data
